"""Map from CVC Exchange college names/slugs back to ASSIST institution codes.

CVC's UI identifies colleges by full display name (e.g. "Santa Monica
College") or numeric `university_id` that is internal to Quottly. ASSIST
uses short codes ("SMCC"). This module bridges the two.

Populated incrementally. If a CVC record comes in with a name not in the
map, `cvc_fetcher` logs a warning and skips it rather than guessing.
"""
from __future__ import annotations

from typing import Dict, Optional


# Keys are CVC display names lowercased with whitespace normalized.
# Values are trimmed ASSIST codes as stored in institutions.code.
NAME_TO_CODE: Dict[str, str] = {
    "allan hancock college": "AHC",
    "american river college": "ARC",
    "antelope valley college": "AVC",
    "bakersfield college": "BAKERFLD",
    "barstow community college": "BARSTOW",
    "berkeley city college": "VISTA",
    "butte college": "BUTTE",
    "cabrillo college": "CABRILLO",
    "canada college": "CANADA",
    "cañada college": "CANADA",
    "cerritos college": "CERRITOS",
    "cerro coso community college": "CERRO",
    "chabot college": "CHABOT",
    "chaffey college": "CHAFFEY",
    "citrus college": "CITRUS",
    "city college of san francisco": "SFCITY",
    "clovis community college": "CLOVIS",
    "coalinga college": "WHC",
    "coastline community college": "COASTLIN",
    "college of alameda": "ALAMEDA",
    "college of marin": "MARIN",
    "college of san mateo": "MATEO",
    "college of the canyons": "CANYONS",
    "college of the desert": "DESERT",
    "college of the redwoods": "REDWOODS",
    "college of the sequoias": "SEQUOIAS",
    "college of the siskiyous": "SISKIYOU",
    "columbia college": "COLUMBIA",
    "compton college": "COMPTON",
    "contra costa college": "CONTRA",
    "copper mountain college": "COPPER",
    "cosumnes river college": "CRC",
    "crafton hills college": "CRAFTON",
    "cuesta college": "CUESTA",
    "cuyamaca college": "CUYAMACA",
    "cypress college": "CYPRESS",
    "de anza college": "DAC",
    "diablo valley college": "DIABLO",
    "east los angeles college": "LAEC",
    "el camino college": "CAMINO",
    "evergreen valley college": "EVERGRN",
    "feather river college": "FEATHER",
    "folsom lake college": "FOLSOM",
    "foothill college": "FOOTHILL",
    "fresno city college": "FRESNO",
    "fullerton college": "FULLRTON",
    "gavilan college": "GAVILAN",
    "glendale community college": "GLENDALE",
    "golden west college": "GWC",
    "grossmont college": "GMCC",
    "hartnell college": "HARTNELL",
    "imperial valley college": "IMPERIAL",
    "irvine valley college": "IRVINE",
    "lake tahoe community college": "TAHOE",
    "laney college": "LANEY",
    "las positas college": "POSITAS",
    "lassen community college": "LASSEN",
    "lemoore college": "WHCL",
    "long beach city college": "LBCC",
    "los angeles city college": "LACC",
    "los angeles harbor college": "LAHC",
    "los angeles mission college": "LAMC",
    "los angeles pierce college": "LAPC",
    "los angeles southwest college": "LASC",
    "los angeles trade technical college": "LATT",
    "los angeles trade-technical college": "LATT",
    "los angeles valley college": "LAVC",
    "los medanos college": "MEDANOS",
    "madera community college": "MCC",
    "mendocino college": "MENDOCIN",
    "merced college": "MERCED",
    "merritt college": "MERRITT",
    "miracosta college": "MIRACSTA",
    "mission college": "MISSION",
    "modesto junior college": "MODESTO",
    "monterey peninsula college": "MONTEREY",
    "moorpark college": "MOORPARK",
    "moreno valley college": "MVC",
    "mount san antonio college": "MTSAC",
    "mt. san antonio college": "MTSAC",
    "mt. san jacinto college": "MTSJC",
    "napa valley college": "NAPA",
    "norco college": "NORCO",
    "ohlone college": "OHLONE",
    "orange coast college": "OCC",
    "oxnard college": "OXNARD",
    "palo verde college": "PALOVRDE",
    "palomar college": "PALOMAR",
    "pasadena city college": "PASADENA",
    "porterville college": "PORTER",
    "reedley college": "KRC",
    "rio hondo college": "RIOHONDO",
    "riverside city college": "RCC",
    "sacramento city college": "SCC",
    "saddleback college": "SADDLBK",
    "san bernardino valley college": "SBVC",
    "san diego city college": "SDCC",
    "san diego mesa college": "MESA",
    "san diego miramar college": "MIRAMAR",
    "san joaquin delta college": "SJDELTA",
    "san jose city college": "SJCC",
    "santa ana college": "RSC",
    "santa barbara city college": "SBCC",
    "santa monica college": "SMCC",
    "santa rosa junior college": "SRC",
    "santiago canyon college": "SANTIAGO",
    "shasta college": "SHASTA",
    "sierra college": "SIERRA",
    "skyline college": "SKYLINE",
    "solano community college": "SOLANO",
    "southwestern college": "SWSTRN",
    "taft college": "TAFT",
    "ventura college": "VENTURA",
    "victor valley college": "VVCC",
    "west los angeles college": "LAWC",
    "west valley college": "WVC",
    "woodland community college": "WCC",
    "yuba college": "YUBA",
}


def lookup(cvc_name: str) -> Optional[str]:
    """Return the ASSIST code for a CVC college name, or None if unknown."""
    if not cvc_name:
        return None
    key = " ".join(cvc_name.strip().lower().split())
    return NAME_TO_CODE.get(key)
